<?php
/**
 * ContactImportBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Planfix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planfix REST API
 *
 * Documentation for Planfix REST API. <br> Generated <a href=\"https://root/restapidocs/swagger.json\">swagger.json</a>
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.44
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Planfix;

use PHPUnit\Framework\TestCase;

/**
 * ContactImportBodyTest Class Doc Comment
 *
 * @category    Class
 * @description ContactImportBody
 * @package     Planfix
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContactImportBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ContactImportBody"
     */
    public function testContactImportBody()
    {
    }

    /**
     * Test attribute "sourceId"
     */
    public function testPropertySourceId()
    {
    }

    /**
     * Test attribute "contactTemplateId"
     */
    public function testPropertyContactTemplateId()
    {
    }

    /**
     * Test attribute "companyTemplateId"
     */
    public function testPropertyCompanyTemplateId()
    {
    }

    /**
     * Test attribute "optionImportDuplicate"
     */
    public function testPropertyOptionImportDuplicate()
    {
    }

    /**
     * Test attribute "optionImportUniqueField"
     */
    public function testPropertyOptionImportUniqueField()
    {
    }

    /**
     * Test attribute "optionImportUniqueDefaultField"
     */
    public function testPropertyOptionImportUniqueDefaultField()
    {
    }

    /**
     * Test attribute "contacts"
     */
    public function testPropertyContacts()
    {
    }
}
