<?php
/**
 * ContactResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Planfix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planfix REST API
 *
 * Documentation for Planfix REST API. <br> Generated <a href=\"https://root/restapidocs/swagger.json\">swagger.json</a>
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.44
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Planfix;

use PHPUnit\Framework\TestCase;

/**
 * ContactResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ContactResponse
 * @package     Planfix
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContactResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ContactResponse"
     */
    public function testContactResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "templateId"
     */
    public function testPropertyTemplateId()
    {
    }

    /**
     * Test attribute "sourceObjectId"
     */
    public function testPropertySourceObjectId()
    {
    }

    /**
     * Test attribute "sourceDataVersion"
     */
    public function testPropertySourceDataVersion()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "midname"
     */
    public function testPropertyMidname()
    {
    }

    /**
     * Test attribute "lastname"
     */
    public function testPropertyLastname()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "skype"
     */
    public function testPropertySkype()
    {
    }

    /**
     * Test attribute "telegramId"
     */
    public function testPropertyTelegramId()
    {
    }

    /**
     * Test attribute "telegram"
     */
    public function testPropertyTelegram()
    {
    }

    /**
     * Test attribute "facebook"
     */
    public function testPropertyFacebook()
    {
    }

    /**
     * Test attribute "instagram"
     */
    public function testPropertyInstagram()
    {
    }

    /**
     * Test attribute "vk"
     */
    public function testPropertyVk()
    {
    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {
    }

    /**
     * Test attribute "isCompany"
     */
    public function testPropertyIsCompany()
    {
    }

    /**
     * Test attribute "isDeleted"
     */
    public function testPropertyIsDeleted()
    {
    }

    /**
     * Test attribute "birthDate"
     */
    public function testPropertyBirthDate()
    {
    }

    /**
     * Test attribute "dateOfLastUpdate"
     */
    public function testPropertyDateOfLastUpdate()
    {
    }

    /**
     * Test attribute "supervisors"
     */
    public function testPropertySupervisors()
    {
    }

    /**
     * Test attribute "phones"
     */
    public function testPropertyPhones()
    {
    }

    /**
     * Test attribute "companies"
     */
    public function testPropertyCompanies()
    {
    }

    /**
     * Test attribute "contacts"
     */
    public function testPropertyContacts()
    {
    }

    /**
     * Test attribute "customFieldData"
     */
    public function testPropertyCustomFieldData()
    {
    }
}
