<?php
/**
 * DirectoryEntryResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Planfix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planfix REST API
 *
 * Documentation for Planfix REST API. <br> Generated <a href=\"https://root/restapidocs/swagger.json\">swagger.json</a>
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.44
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Planfix;

use PHPUnit\Framework\TestCase;

/**
 * DirectoryEntryResponseTest Class Doc Comment
 *
 * @category    Class
 * @description DirectoryEntryResponse
 * @package     Planfix
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DirectoryEntryResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DirectoryEntryResponse"
     */
    public function testDirectoryEntryResponse()
    {
    }

    /**
     * Test attribute "directory"
     */
    public function testPropertyDirectory()
    {
    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {
    }

    /**
     * Test attribute "parentKey"
     */
    public function testPropertyParentKey()
    {
    }

    /**
     * Test attribute "archived"
     */
    public function testPropertyArchived()
    {
    }

    /**
     * Test attribute "isGroup"
     */
    public function testPropertyIsGroup()
    {
    }

    /**
     * Test attribute "customFieldData"
     */
    public function testPropertyCustomFieldData()
    {
    }
}
