<?php
/**
 * TaskResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Planfix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planfix REST API
 *
 * Documentation for Planfix REST API. <br> Generated <a href=\"https://root/restapidocs/swagger.json\">swagger.json</a>
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.44
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Planfix;

use PHPUnit\Framework\TestCase;

/**
 * TaskResponseTest Class Doc Comment
 *
 * @category    Class
 * @description TaskResponse
 * @package     Planfix
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TaskResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TaskResponse"
     */
    public function testTaskResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "sourceObjectId"
     */
    public function testPropertySourceObjectId()
    {
    }

    /**
     * Test attribute "sourceDataVersion"
     */
    public function testPropertySourceDataVersion()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "processId"
     */
    public function testPropertyProcessId()
    {
    }

    /**
     * Test attribute "resultChecking"
     */
    public function testPropertyResultChecking()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "assigner"
     */
    public function testPropertyAssigner()
    {
    }

    /**
     * Test attribute "parent"
     */
    public function testPropertyParent()
    {
    }

    /**
     * Test attribute "template"
     */
    public function testPropertyTemplate()
    {
    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {
    }

    /**
     * Test attribute "counterparty"
     */
    public function testPropertyCounterparty()
    {
    }

    /**
     * Test attribute "dateTime"
     */
    public function testPropertyDateTime()
    {
    }

    /**
     * Test attribute "startDateTime"
     */
    public function testPropertyStartDateTime()
    {
    }

    /**
     * Test attribute "endDateTime"
     */
    public function testPropertyEndDateTime()
    {
    }

    /**
     * Test attribute "hasStartDate"
     */
    public function testPropertyHasStartDate()
    {
    }

    /**
     * Test attribute "hasEndDate"
     */
    public function testPropertyHasEndDate()
    {
    }

    /**
     * Test attribute "hasStartTime"
     */
    public function testPropertyHasStartTime()
    {
    }

    /**
     * Test attribute "hasEndTime"
     */
    public function testPropertyHasEndTime()
    {
    }

    /**
     * Test attribute "delayedTillDate"
     */
    public function testPropertyDelayedTillDate()
    {
    }

    /**
     * Test attribute "dateOfLastUpdate"
     */
    public function testPropertyDateOfLastUpdate()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "durationUnit"
     */
    public function testPropertyDurationUnit()
    {
    }

    /**
     * Test attribute "durationType"
     */
    public function testPropertyDurationType()
    {
    }

    /**
     * Test attribute "overdue"
     */
    public function testPropertyOverdue()
    {
    }

    /**
     * Test attribute "closeToDeadLine"
     */
    public function testPropertyCloseToDeadLine()
    {
    }

    /**
     * Test attribute "notAcceptedInTime"
     */
    public function testPropertyNotAcceptedInTime()
    {
    }

    /**
     * Test attribute "inFavorites"
     */
    public function testPropertyInFavorites()
    {
    }

    /**
     * Test attribute "isSummary"
     */
    public function testPropertyIsSummary()
    {
    }

    /**
     * Test attribute "isSequential"
     */
    public function testPropertyIsSequential()
    {
    }

    /**
     * Test attribute "assignees"
     */
    public function testPropertyAssignees()
    {
    }

    /**
     * Test attribute "participants"
     */
    public function testPropertyParticipants()
    {
    }

    /**
     * Test attribute "auditors"
     */
    public function testPropertyAuditors()
    {
    }

    /**
     * Test attribute "recurrence"
     */
    public function testPropertyRecurrence()
    {
    }

    /**
     * Test attribute "isDeleted"
     */
    public function testPropertyIsDeleted()
    {
    }

    /**
     * Test attribute "customFieldData"
     */
    public function testPropertyCustomFieldData()
    {
    }
}
