<?php
/**
 * EmployeeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Planfix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planfix REST API
 *
 * Documentation for Planfix REST API. <br> Generated <a href=\"https://root/restapidocs/swagger.json\">swagger.json</a>
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.44
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Planfix;

use Planfix\Configuration;
use Planfix\ApiException;
use Planfix\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EmployeeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Planfix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EmployeeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getUserId
     *
     * Get employee by number.
     *
     */
    public function testGetUserId()
    {
    }

    /**
     * Test case for getUserList
     *
     * Get list of employees.
     *
     */
    public function testGetUserList()
    {
    }

    /**
     * Test case for getUserListGroups
     *
     * Get list of employee groups.
     *
     */
    public function testGetUserListGroups()
    {
    }

    /**
     * Test case for getUserPosts
     *
     * Get list of employee posts.
     *
     */
    public function testGetUserPosts()
    {
    }

    /**
     * Test case for postUser
     *
     * Create employee.
     *
     */
    public function testPostUser()
    {
    }

    /**
     * Test case for postUserId
     *
     * Update employee by number.
     *
     */
    public function testPostUserId()
    {
    }
}
