<?php
/**
 * TaskApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Planfix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Planfix REST API
 *
 * Documentation for Planfix REST API. <br> Generated <a href=\"https://root/restapidocs/swagger.json\">swagger.json</a>
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.44
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Planfix;

use Planfix\Configuration;
use Planfix\ApiException;
use Planfix\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TaskApiTest Class Doc Comment
 *
 * @category Class
 * @package  Planfix
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TaskApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getTaskById
     *
     * Get task by number.
     *
     */
    public function testGetTaskById()
    {
    }

    /**
     * Test case for getTaskComments
     *
     * Get task comments.
     *
     */
    public function testGetTaskComments()
    {
    }

    /**
     * Test case for getTaskList
     *
     * Get list of tasks.
     *
     */
    public function testGetTaskList()
    {
    }

    /**
     * Test case for getTaskListTemplates
     *
     * Get list of task templates.
     *
     */
    public function testGetTaskListTemplates()
    {
    }

    /**
     * Test case for postTask
     *
     * Create task.
     *
     */
    public function testPostTask()
    {
    }

    /**
     * Test case for postTaskAddComment
     *
     * Add comment.
     *
     */
    public function testPostTaskAddComment()
    {
    }

    /**
     * Test case for postTaskAddDataTagEntryExistingComment
     *
     * Add a data tag entry to an existing comment.
     *
     */
    public function testPostTaskAddDataTagEntryExistingComment()
    {
    }

    /**
     * Test case for postTaskAddDataTagEntryNewComment
     *
     * Add data tag entry as new comment.
     *
     */
    public function testPostTaskAddDataTagEntryNewComment()
    {
    }

    /**
     * Test case for postTaskById
     *
     * Update task by number.
     *
     */
    public function testPostTaskById()
    {
    }

    /**
     * Test case for postTaskFilters
     *
     * Get list task filters.
     *
     */
    public function testPostTaskFilters()
    {
    }

    /**
     * Test case for postTaskUpdateComment
     *
     * Updating comments.
     *
     */
    public function testPostTaskUpdateComment()
    {
    }
}
